device:
  layer: rpi5
  hostname: raspiaudio

image:
  layer: image-rpios
  boot_part_size: 256M
  root_part_size: 8192M
  name: raspiaudio-dspbox-pi5

layer:
  base: bookworm-minbase
  custom: raspiaudio-appliance
